package com.dhcc.visa.ui.widget.pinyin;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.


import java.io.Serializable;

/**
 * Entity mapped to table FRIEND.
 */
public class Country implements Serializable {

    private static final long serialVersionUID = 8270277246566381723L;
    /**
     * Not-null value.
     */
    private String name;
    private String displayName;
    private String letters;

    public String getLetters() {
        return letters;
    }

    public void setLetters(String letters) {
        this.letters = letters;
    }

    public Country() {
    }


    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
